pipeline {
    agent any

    environment {
        ANDROID_HOME = '/home/ext_rmadan_vecv_in/android-sdk'
        GRADLE_USER_HOME = "${HOME}/.gradle"
        FLUTTER_HOME = '/home/ext_rmadan_vecv_in/flutter-sdk/flutter'
        PATH = "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$FLUTTER_HOME/bin:$PATH"
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

       

        stage('Set Up Environment') {
            steps {
                sh '''
                    yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
                    $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
                        "platform-tools" "platforms;android-34" "build-tools;29.0.2"
                '''
            }
        }

        stage('Build Debug APK') {
            steps {
                sh '''
                    # Build Debug APK
                    $FLUTTER_HOME/bin/flutter clean
                    $FLUTTER_HOME/bin/flutter pub get
                    $FLUTTER_HOME/bin/flutter build apk --debug
                '''
            }
        }
    }

