pipeline {
    agent any

    environment {
        ANDROID_HOME = '/home/ext_rmadan_vecv_in/android-sdk'
        FLUTTER_HOME = '/home/ext_rmadan_vecv_in/flutter-sdk/flutter'
        GRADLE_USER_HOME = "${HOME}/.gradle"
        PATH = "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$FLUTTER_HOME/bin:$PATH"
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Fix Flutter SDK Permissions') {
            steps {
                sh '''
                    # Fix permissions for Flutter SDK
                    chown -R $USER:$USER $FLUTTER_HOME
                '''
            }
        }

        

        stage('Flutter Install') {
            steps {
                sh '''
                    # Ensure Flutter is installed and check the environment
                    flutter doctor
                '''
            }
        }

        stage('Build Debug APK') {
            steps {
                sh '''
                    # Build Debug APK (no signing)
                    flutter build apk --debug
                '''
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: '**/*.apk', allowEmptyArchive: true
            }
        }
    }
}
